version: '2'

services:
  zookeeper:
    container_name: zookeeper
    image: marekstachura/zookeeper-docker
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_MAXCLIENTCNXNS: 0

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:0.8.1.1-1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
  redis:
    container_name: redis
    image: redis
    ports: 
      - 6379:6379
  cassandra:
    image: cassandra:2.1
    ports:
      - "9042/tcp:9042/tcp"
      - "7199/tcp:7199/tcp"
    container_name: cassandra


